- name: "Creates directory"
  file:
    path: "/home/ubuntu/server"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "/home/ubuntu/server/artifact-backend.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "/home/ubuntu/server/artifact-backend.tar.gz"
    dest: "/home/ubuntu/server"

- name: "Run the web server"
  shell:
    cmd: |
      cd /home/ubuntu/server
      npm install
      npm audit fix --force --audit-level=critical
      pm2 stop default
      pm2 start npm -- start --wait-ready